services:
  app:
    container_name: app
    build: ./app
    ports:
      - 8000:8000
    env_file:
      - ./app/.env
    volumes:
      - ./app:/app
    
  db:
    container_name: db
    image: mysql:8.0-bookworm
    env_file:
      - ./app/.env
